// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface CloudflareEnv {
    AI: AI;
    BUCKET: R2Bucket;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_API_TOKEN: string;
  }
  