#:schema node_modules/wrangler/config-schema.json
name = "whisper"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# MY_VARIABLE = "production_value"
CLOUDFLARE_ACCOUNT_ID="你的账户id"
CLOUDFLARE_API_TOKEN="你的apitoken"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#workers-ai
[ai]
binding = "AI"

